### ISSUE TITLE
Blocks Display Mode Change (Integrated/Dedicated GPU)

### ISSUE THREAD

**Issue by lukasong** [srwi/EverythingToolbar#361] opened 2023-04-08 20:50 UTC
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.3.0

### Windows Version

Windows 11 Build 22621

### Steps to reproduce

1. Have integrated and dedicated graphics.
2. Have automatic switching between the two, or try to manually.
3. Have everything toolbar running.

### Expected Behavior

Display mode switches between GPUs.

### Actual Behavior

Pop up with "unable to switch display modes" because of EverythingToolbar.Launcher.exe.

### Screenshots

![image](https://user-images.githubusercontent.com/22720383/230742052-d7f6d9ba-bc15-4c40-a892-fb8ed8418120.png)

### Log output

2023-04-08 14:53:38.5228|INFO|Launcher|EverythingToolbar Launcher 1.0.3.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-04-08 16:04:13.2031|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by Horst12** [comment] 2023-04-10 15:49
The Everything toolbar is all the time running here.
I have configured the use of the Dedicated GPU (NVidea) for the browser and some file managers.
There is no conflict here and the graphics are automatically switched iby Windows.
______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.1495)
Everything 1.5.0.1341a (x64)
Everything Toolbar 1.0.3.0

**Comment by srwi** [comment] 2023-04-10 17:32
Could you please try the solution mentioned [here](https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Override_Blocking_Programs.htm)? It looks like this should prevent EverythingToolbar from preventing the display mode change.

Unfortunately I don't know why it would block the switch and I don't have the hardware setup to reproduce the issue.

**Closed** 2023-05-05 18:32 UTC
