### ISSUE TITLE
Move filters to dropdown on demand

### ISSUE THREAD

**Issue by 601958483** [srwi/EverythingToolbar#472] opened 2023-12-06 09:37 UTC
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

希望可以直接将搜索的“更多”项里的多个选项拖放至一级目录展示，方便直接点击使用
![Clip_20231206_172927](https://github.com/srwi/EverythingToolbar/assets/43309053/815d97c1-762b-44a2-8a63-9e7d8d029c7e)

### Proposed Solution

![tempory 拷贝](https://github.com/srwi/EverythingToolbar/assets/43309053/d4a1b0b2-be97-4566-a554-25e9a189ea85)
bi'ru比如类似如此

### Alternatives Considered

或者缩小些，可以全部显示

**Comment by srwi** [comment] 2024-04-14 12:37
I realized this is a duplicate of #165.

**Closed by srwi** 2024-04-14 12:37 UTC
Labels: enhancement
