### ISSUE TITLE
Misaligned launcher search window

### ISSUE THREAD

**Issue by eljesus111** [srwi/EverythingToolbar#328] opened 2023-02-08 20:49 UTC
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

*

### Proposed Solution

I saw that i can resize and place the start menu at any part of the screen, so why not making that position permanent? It would be cool to have the search menu at any part of the screen, it would be waaay more comfortable than the original start menu.

### Alternatives Considered

*

### Additional Information

*

**Comment by TeacherGalante** [comment] 2023-02-16 12:54
Yes, something similar to the way that SystemTrayMenu allows you to reposition its menu and remembers it would be great.

**Comment by TeacherGalante** [comment] 2023-02-16 22:03
I am attaching a screenshot of my desktop. I'm really more asking for the toolbar to pop up centred or aligned with the pinned toolbar icon. I think my main issue is that being left-aligned feels "off" when I am able to centre-align the icons. I did try left-aligning the start bar, then re-centring them, but that did not re-align the toolbar popup. Does that explanation make sense?
![desktop-why-move-the-everything-toolbar](https://user-images.githubusercontent.com/107283796/219496587-35d9f540-5fad-4821-a7d1-638e30b4fb93.jpg)

**Comment by eljesus111** [comment] 2023-02-17 05:20
> I must honestly say I don't really like the idea. EverythingToolbar is meant to mimic the behavior of the original Windows search and therefore positions itself near the search icon/box. Allowing the user to place the windows freely would require an additional option/button to revert the behavior to automatic placement.
> 
> What would be a scenario where you want to place the search window away from the search icon/box?

Well, basically the dude above me answered for me. I mean, it would be waaaaaaaay easier to customize your ui (centering the menu as an example)

**Comment by srwi** [comment] 2023-02-17 22:09
@TeacherGalante Actually the search window should be placed in the middle of the screen in your case. Could you please attach the contents of the log file (`%TEMP%\EverythingToolbar.log`) and check the registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarAl`? For a center aligned taskbar the value should be `1`.

**Comment by eljesus111** [comment] 2023-02-18 01:05
> @TeacherGalante Actually the search window should be placed in the middle of the screen in your case. Could you please attach the contents of the log file (`%TEMP%\EverythingToolbar.log`) and check the registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarAl`? For a center aligned taskbar the value should be `1`.

it would be cool a centered search menu on windows 10, mixed with explorer patcher's centered start menu.

**Comment by TeacherGalante** [comment] 2023-02-18 20:03
@srwi 

> @TeacherGalante Actually the search window should be placed in the middle of the screen in your case. Could you please attach the contents of the log file (`%TEMP%\EverythingToolbar.log`) and check the registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarAl`? For a center aligned taskbar the value should be `1`.

Contents of the log file:
2023-02-18 14:59:56.5197|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-02-18 15:01:29.5833|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

The registry value for TaskbarA1 was set to 0; I manually edited the value to 1 and restarted the system. It did not fix the issue.

**Comment by srwi** [comment] 2023-02-21 18:48
> @srwi
> 
> > @TeacherGalante Actually the search window should be placed in the middle of the screen in your case. Could you please attach the contents of the log file (`%TEMP%\EverythingToolbar.log`) and check the registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarAl`? For a center aligned taskbar the value should be `1`.
> 
> Contents of the log file: 2023-02-18 14:59:56.5197|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1| 2023-02-18 15:01:29.5833|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
> 
> The registry value for TaskbarA1 was set to 0; I manually edited the value to 1 and restarted the system. It did not fix the issue.

Sorry, I forgot to ask which build version of Windows 11 are you running?

I must admit, I don't see any reason why it would align itself on the left side. It should be center-aligned if you are running Windows 11 (at least build number 22000) **and** the registry key `TaskbarAl` has value `1`. Are you sure the registry key exists under `TaskbarAl` (as in "TaskbarAlignment") and not `TaskbarA1`?

**Comment by TeacherGalante** [comment] 2023-02-21 22:02
@srwi Wellllll...now that you mention it, there *is* no "TaskbarAlignment" under the HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ branch. I'll add it, set it to "1", and let you know how it goes.

**Comment by TeacherGalante** [comment] 2023-02-22 04:27
I apologise I didn't see your request earlier for the Windows version. It is: 
Edition	Windows 11 Home
Version	22H2
Installed on	‎05/‎10/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by srwi** [comment] 2023-02-26 15:14
Sorry for my slow responses regarding this issue. I am still a little clueless here. I just published a new release 1.0.3 of EverythingToolbar. I added some more debugging output to hopefully get to the bottom of this. It would be great if you could help me by doing the following:

- To enable the increased debugging output level please create a file named `debug.txt` in the directory `%APPDATA%\EverythingToolbar`

    > Remember to unhide file extensions in Windows explorer. Otherwise the file might end up being called `debug.txt.txt` or similar.

- Restart EverythingToolbar by closing it from the system tray (bottom right)
- Reopen the search window
- Paste the newly created contents of the log file here.

If the file `debug.txt` was created correctly, the log file should contain a line "Debug logging enabled.".

**Comment by eljesus111** [comment] 2023-02-28 01:28
i have no idea what to say

**Comment by adrynalyne** [comment] 2023-02-28 15:23
@srwi I have the same issue/concern. My TaskbarAl is set to 1, and I am on Windows 11 with a centered taskbar. EverythingToolbar opens to the top left on my ultrawide monitor. Other times it will open in the center, and other items it will be halfway off the screen. I am running 1.0.3, and I tried enabling the debug.txt but nothing was ever written to it.

I tried the following locations:
%APPDATA%\EverythingToolbar\debug.txt --This required building the directory structure firs.
%LOCALAPPDATA%\EverythingToolbar\debug.txt  --This directory existed already, but still nothing was written.
I restarted Everything Toolbar and even rebooted.

**Comment by srwi** [comment] 2023-03-03 23:38
@adrynalyne It looks like there is some application pinned to the left screen edge with a width of one pixel. This tricks EverythingToolbar into thinking the taskbar was vertical at the left edge of the screen. Can you imagine which application could be causing this? My first thought was the Windows widgets sidebar, but I can't reproduce the problem by enabling that on my machine. 

In @TeacherGalante's screenshot I see applications like maybe Rainmeter causing that. 

In the end it's hard for me to say what exactly is causing this, but I can probably fix this for most cases by prioritizing the bottom over the left taskbar position.

**Comment by TeacherGalante** [comment] 2023-03-08 19:14
> @adrynalyne It looks like there is some application pinned to the left screen edge with a width of one pixel. This tricks EverythingToolbar into thinking the taskbar was vertical at the left edge of the screen. Can you imagine which application could be causing this? My first thought was the Windows widgets sidebar, but I can't reproduce the problem by enabling that on my machine.
> 
> In @TeacherGalante's screenshot I see applications like maybe Rainmeter causing that.
> 
> In the end it's hard for me to say what exactly is causing this, but I can probably fix this for most cases by prioritizing the bottom over the left taskbar position.

I tried disabling Rainmeter; the same issue occurs.

One other item of note: whenever I attempt to change the alignment of the start bar in Windows's settings, it automatically resets back to left alignment immediately. For example, I click centre alignment; Windows allows the dropdown to select centre alignment; immediately, Windows resets the setting to left alignment while I am looking at the screen.

**Comment by srwi** [comment] 2023-03-09 21:53
> One other item of note: whenever I attempt to change the alignment of the start bar in Windows's settings, it automatically resets back to left alignment immediately. For example, I click centre alignment; Windows allows the dropdown to select centre alignment; immediately, Windows resets the setting to left alignment while I am looking at the screen.

There seems to be an unrelated problem with your Windows installation, probably caused by some other application.

I implemented a workaround that I expect to fix the issues related to EverythingToolbar. It will be available in the next release. I will close this issue now. If it does not solve the problem, please open another bug report.

**Closed by srwi** 2023-03-09 21:53 UTC
Labels: bug, info/repro needed
