### ISSUE TITLE
Make the search result box size no longer automatically change

### ISSUE THREAD

**Issue by cangzhouyuhe** [srwi/EverythingToolbar#434] opened 2023-09-04 06:29 UTC
### Preflight Checklist

- [x] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

V0.12.00
When manually lowering Search Results Box's height (even when running in administrator mode) will still gradually increase in height and size, just like the following gif
![截图_20230904141742](https://github.com/srwi/EverythingToolbar/assets/50189901/e7f295ef-c8d5-43a9-84da-6df2fb2d39a3)

### Proposed Solution

Manually adjust the size of the search result box so that it no longer automatically changes

### Alternatives Considered

Make the size of the search result box no longer automatically change

**Comment by cangzhouyuhe** [comment] 2024-06-20 14:37
Why not fix this issue and choose to close it? I think most people would choose to "automatically hide the status bar", which would result in the height of the toolbar being unable to be fixed and constantly increasing, making it too uncomfortable to use.Please

**Comment by srwi** [comment] 2024-06-20 14:49
> Why not fix this issue and choose to close it? 

I just closed the duplicate of the issue you created. As long as this issue right here is open, it's on the radar and will be fixed once the time (or another contributor) comes.

**Comment by cangzhouyuhe** [comment] 2024-06-20 14:53
> > Why not fix this issue and choose to close it?为什么不解决此问题并选择关闭它？
> 
> I just closed the duplicate of the issue you created. As long as this issue right here is open, it's on the radar and will be fixed once the time (or another contributor) comes.我刚刚关闭了您创建的问题的副本。只要这里的这个问题是开放的，它就会受到关注，一旦时机（或其他贡献者）到来，它就会得到解决。

Thank you！

**Comment by srwi** [comment] 2024-06-20 22:58
I had some time today and implemented a fix for the scaling issue. It will be available in the next release of EverythingToolbar!

**Closed by srwi** 2024-06-20 22:58 UTC
Labels: bug, deskband
