### ISSUE TITLE
needs to be suspended in the center of the screen

### ISSUE THREAD

**Issue by hunterHungry** [srwi/EverythingToolbar#495] opened 2024-04-23 05:28 UTC
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I set the windows button on the left side of the screen. When I use everthing, its input box appears on the left side, which feels weird. Especially when using a large screen, it brings a lot of inconvenience

### Proposed Solution

Ability to customize the location where the search box appears

### Alternatives Considered

N/A

**Comment by srwi** [comment] 2024-04-25 16:36
Why does it feel weird to align the search box with the Windows icon? Doesn't the Start menu behave the same way? Currently it is like this by design. 

Are you using third party applications to detach the Windows icon from the other taskbar icons? If so, changing this would be out of scope.

**Comment by hunterHungry** [comment] 2024-04-26 04:16
> Why does it feel weird to align the search box with the Windows icon? Doesn't the Start menu behave the same way? Currently it is like this by design.
> 
> Are you using third party applications to detach the Windows icon from the other taskbar icons? If so, changing this would be out of scope.

In the windows setting, It can change windows start icon to left. I prefer to old start icon location.

**Closed** 2024-04-26 06:27 UTC
