### ISSUE TITLE
Explorer.exe crashes when typing certain words

### ISSUE THREAD

**Issue by hyperactive68** [srwi/EverythingToolbar#383] opened 2023-05-13 17:56 UTC
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.5

### Windows Version

Windows 10 Home 21H2

### Steps to reproduce

1. Type "subby" or "resanan" in the toolbar

### Expected Behavior

Showing me the results for what I typed

### Actual Behavior

Explorer.exe crashes

### Log output

2023-05-13 19:52:43.8313|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.0.5.0 started. OS: Microsoft Windows NT 10.0.19044.0|
2023-05-13 19:52:47.6083|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-13 19:52:51.4365|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.0.5.0 started. OS: Microsoft Windows NT 10.0.19044.0|

### Additional Information

I only happened to come across those 2 words not working. There might be even more. It happens consistently, but not when I'm using Everything by itself. Explorer.exe only crashes using the toolbar.

**Comment by srwi** [comment] 2023-05-13 18:01
Hi @hyperactive68, what are the search results you get in regular Everything when searching for either of those terms? It is probably linked to the spoecific files on your machine, so it would be great if you could identify which files exactly are causing this problem.

**Comment by Horst12** [comment] 2023-05-13 18:04
There are no such crashes at least in my Windows 11.

I guess you have some other software or script in the background.
The toolbar just uses the SDK to query Everything
and you said Everything itself works with your magic words.
______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.1702)
Everything 1.5.0.1346a (x64)
Everything Toolbar 1.0.5.0

**Comment by hyperactive68** [comment] 2023-05-13 21:16
> Hi @hyperactive68, what are the search results you get in regular Everything when searching for either of those terms? It is probably linked to the spoecific files on your machine, so it would be great if you could identify which files exactly are causing this problem.

So I tried deleting every file associated with "subby" (for context: [it's a tool for extracting plex subtitles](https://github.com/devilismyfriend/subby). After deleting everything, the word doesn't cause explorer.exe to crash anymore. I tried downloading it again to see if it crashes again, and nothing... So I don't know what's going on.


> There are no such crashes at least in my Windows 11.
> 
> I guess you have some other software or script in the background. The toolbar just uses the SDK to query Everything and you said Everything itself works with your magic words.
> 
> Windows 11 Home x64 Version 22H2 (OS Build 22621.1702) Everything 1.5.0.1346a (x64) Everything Toolbar 1.0.5.0

Yes, which is why I'm confused. I'm not running any scripts.

**Comment by srwi** [comment] 2023-05-17 18:26
> So I tried deleting every file associated with "subby" (for context: [it's a tool for extracting plex subtitles](https://github.com/devilismyfriend/subby)). After deleting everything, the word doesn't cause explorer.exe to crash anymore. I tried downloading it again to see if it crashes again, and nothing... So I don't know what's going on.

It might be related to EverythingToolbar loading the file thumbnails, but it's hard to tell without access to the files to reproduce the crash. I suggest closing the issue for now, since the problem seems to be resolved for you. Please reopen the issue once you are experiencing the problem again.

**Closed by srwi** 2023-05-17 18:26 UTC

**Comment by shodanx2** [comment] 2023-05-20 02:14
Hi there, 
Just wanted to chime in 
I'm also getting explorer crashing with everythingtoolbar
I've stopped using it for the time being until I can do a fresh windows installation and control variables to narrow down the cause

I know in my case it has to do with everythingtoolbar's  flyout taking wonky dimensions such as the entire monitor and appearing on the wrong monitor

**Comment by srwi** [comment] 2023-05-20 08:04
@shodanx2 Which version of EverythingToolbar have you had this problem with? 1.0.3 or 1.0.5?

**Comment by shodanx2** [comment] 2023-05-22 20:39
I stopped using it a while ago. 
I just checked it was 1.0.3

I will update now and observe if the problem remains
