### ISSUE TITLE
It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### ISSUE THREAD

**Issue by nljxlove** [srwi/EverythingToolbar#369] opened 2023-04-12 03:17 UTC
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### Proposed Solution

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### Alternatives Considered

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

**Comment by srwi** [comment] 2023-04-12 05:59
Duplicate of #255.

**Closed by srwi** 2023-04-12 05:59 UTC
